org: ghost1608
app: appointment-backend
service: appointment-backend

frameworkVersion: '4'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION, "us-east-1"}

  environment:
    REGION: ${env:REGION, "us-east-1"}

    APPOINTMENT_TABLE:
      Ref: AppointmentTable

    APPOINTMENT_CREATED_TOPIC_ARN:
      Ref: AppointmentCreatedTopic

    APPOINTMENT_EVENT_BUS:
      Ref: AppointmentBus

    # RDS PE
    RDS_HOST_PE: ${env:RDS_HOST_PE, ssm:/appointment-backend/rds/host_pe}
    RDS_PORT_PE: ${env:RDS_PORT_PE, ssm:/appointment-backend/rds/port_pe}
    RDS_USER_PE: ${env:RDS_USER_PE, ssm:/appointment-backend/rds/user_pe}
    RDS_PASSWORD_PE: ${env:RDS_PASSWORD_PE, ssm:/appointment-backend/rds/password_pe~true}
    RDS_DATABASE_PE: ${env:RDS_DATABASE_PE, ssm:/appointment-backend/rds/database_pe}

    # RDS CL
    RDS_HOST_CL: ${env:RDS_HOST_CL, ssm:/appointment-backend/rds/host_cl}
    RDS_PORT_CL: ${env:RDS_PORT_CL, ssm:/appointment-backend/rds/port_cl}
    RDS_USER_CL: ${env:RDS_USER_CL, ssm:/appointment-backend/rds/user_cl}
    RDS_PASSWORD_CL: ${env:RDS_PASSWORD_CL, ssm:/appointment-backend/rds/password_cl~true}
    RDS_DATABASE_CL: ${env:RDS_DATABASE_CL, ssm:/appointment-backend/rds/database_cl}

functions:

  appointmentApi:
    handler: dist/infrastructure/lambdas/appointment-api.handler
    events:
      - httpApi:
          path: /appointments
          method: post
      - httpApi:
          path: /appointments/{id}
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource:
          Fn::GetAtt: [AppointmentTable, Arn]
      - Effect: Allow
        Action:
          - sns:Publish
        Resource:
          Ref: AppointmentCreatedTopic

  appointmentPeConsumer:
    handler: dist/infrastructure/lambdas/appointment-consumer-pe.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SqsPEQueue, Arn]
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
        Resource:
          Fn::GetAtt: [SqsPEQueue, Arn]
      - Effect: Allow
        Action:
          - events:PutEvents
        Resource:
          arn:aws:events:${env:REGION}:*:event-bus/${env:APPOINTMENT_EVENT_BUS}
      - Effect: Allow
        Action:
          - rds-db:connect
        Resource: "*"

  appointmentClConsumer:
    handler: dist/infrastructure/lambdas/appointment-consumer-cl.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SqsCLQueue, Arn]
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
        Resource:
          Fn::GetAtt: [SqsCLQueue, Arn]
      - Effect: Allow
        Action:
          - events:PutEvents
        Resource:
          arn:aws:events:${env:REGION}:*:event-bus/${env:APPOINTMENT_EVENT_BUS}
      - Effect: Allow
        Action:
          - rds-db:connect
        Resource: "*"

  appointmentUpdConsumer:
    handler: dist/infrastructure/lambdas/appointment-update.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [AppointmentConfirmationQueue, Arn]
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          Fn::GetAtt: [AppointmentTable, Arn]
resources:
  Resources:

    AppointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appointment-table-${sls:stage}
        AttributeDefinitions:
          - AttributeName: appointmentId
            AttributeType: S
        KeySchema:
          - AttributeName: appointmentId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    AppointmentCreatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: appointment-created-topic-${sls:stage}

    SqsPEQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs-pe-${sls:stage}

    SqsCLQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs-cl-${sls:stage}

    SubPeSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: { Ref: AppointmentCreatedTopic }
        Protocol: sqs
        Endpoint: !GetAtt SqsPEQueue.Arn
        FilterPolicy:
          countryISO:
            - "PE"

    SubClSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: { Ref: AppointmentCreatedTopic }
        Protocol: sqs
        Endpoint: !GetAtt SqsCLQueue.Arn
        FilterPolicy:
          countryISO:
            - "CL"

    AppointmentBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: appointment-bus-${sls:stage}

    AppointmentConfirmationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: appointment-confirmation-queue-${sls:stage}

    AppointmentToConfirmRule:
      Type: AWS::Events::Rule
      Properties:
        Name: appointment-confirm-rule-${sls:stage}
        EventBusName: !Ref AppointmentBus
        EventPattern:
          source:
            - "appointment.service"
          detail-type:
            - "AppointmentConfirmed"
        Targets:
          - Arn: !GetAtt AppointmentConfirmationQueue.Arn
            Id: ConfirmQueueTarget

    SqsPEQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SqsPEQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action: sqs:SendMessage
              Resource: !GetAtt SqsPEQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref AppointmentCreatedTopic

    SqsCLQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref SqsCLQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action: sqs:SendMessage
              Resource: !GetAtt SqsCLQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref AppointmentCreatedTopic

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - dist/**
    - '!src/**'
    - '!test/**'
    - '!migration/**'
    - '!tsconfig.json'
    - '!tsconfig.build.json'
    - '!package-lock.json'
    - '!README.md'
    - '!node_modules/aws-sdk/**'
    - '!docker-compose.yaml'
